import type { LucideIcon } from "lucide-react";
import {
  Archive,
  ArrowDownCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Box,
  CalendarCheck,
  Check,
  CheckCircle,
  ChevronDown,
  Clock,
  Copy,
  Database,
  ExternalLink,
  Folder,
  HelpCircle,
  Image,
  ImagePlus,
  Link,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Moon,
  Maximize2,
  MoreHorizontal,
  Music,
  Pause,
  Pencil,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  QrCode,
  RefreshCw,
  Search,
  Settings,
  Share2,
  Square,
  Star,
  Sun,
  Terminal,
  Trash2,
  Trophy,
  ToggleLeft,
  Volume2,
  ToggleRight,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  X,
  ZoomIn,
} from "lucide-react";
import { twMerge } from "tailwind-merge";

const iconMap: Record<string, LucideIcon> = {
  archive: Archive,
  "arrow-down": ChevronDown,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-next": ArrowRight,
  "arrow-prev": ArrowLeft,
  "arrow-up": ArrowUp,
  barcode: QrCode,
  calendar: CalendarCheck,
  "calendar-check": CalendarCheck,
  chat: MessageCircle,
  check: Check,
  "check-circle": CheckCircle,
  "check-thin": Check,
  close: X,
  "close-fat": X,
  codepen: Terminal,
  copy: Copy,
  "download-fill": Upload,
  download: Upload,
  dots: MoreHorizontal,
  edit: Pencil,
  email: Mail,
  "external-link": ExternalLink,
  folder: Folder,
  "image-up": ImagePlus,
  "info-circle": HelpCircle,
  logout: LogOut,
  marker: MapPin,
  moon: Moon,
  notification: Bell,
  plus: Plus,
  "plus-circle": PlusCircle,
  "plus-circle-stroke": PlusCircle,
  profile: User,
  "profile-1": UserCircle,
  "settings-fill": Settings,
  settings: Settings,
  share: Share2,
  "share-1": Share2,
  stop: Square,
  sun: Sun,
  "toggle-on": ToggleRight,
  "toggle-off": ToggleLeft,
  trash: Trash2,
  "user-check": UserCheck,
  "zoom-in": ZoomIn,
  "search-1": Search,
  search: Search,
  clock: Clock,
  time: Clock,
  "image-check": Image,
  "play-circle": PlayCircle,
  trophy: Trophy,
  "music-note": Music,
  link: Link,
  invite: UserPlus,
  star: Star,
  duplicate: Copy,
  dataflow: Database,
  box: Box,
  pause: Pause,
  volume: Volume2,
  scale: Maximize2,
  refresh: RefreshCw,
  "star-fill": Star,
  "delete-chat": Trash2,
  lock: Lock,
  terminal: Terminal,
};

type IconProps = React.SVGProps<SVGSVGElement> & {
  name?: string;
};

export function Icon({ name, className, ...props }: IconProps) {
  if (!name) return null;
  const LucideIcon = iconMap[name] ?? HelpCircle;
  return (
    <LucideIcon
      className={twMerge("inline-block size-6 shrink-0", className)}
      {...props}
    />
  );
}
